  
# This is a new basic workflow to help you get started with Actions

name: React covid Tracker App Deploy to Surge

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
      runs-on: ubuntu-latest
  
      steps:
      
      - uses: actions/checkout@v2

      - name: Install NodeJS
        uses: actions/setup-node@v2-beta
        with:
          node-version: 12
      
      - uses: borales/actions-yarn@v2.0.0
        with:
          cmd: install
      
      - name: Build React App
        run: yarn build

      - name: Install Surge
        run: npm install --global surge

      - name: Deploy to Surge
        run: surge ./build my-covid-app.surge.sh --token ${{ secrets.NEW_TOKEN }}
